# 1. Files excluded from Jekyll builds
exclude:
- scripts/
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache


# 2. Installed Gems
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
remote_theme: daviddarnes/alembic@main


# 3. Gem settings
paginate: 2 #  jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Tobias Schraink # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Tobias Schraink # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/tschraink
    - https://github.com/tobsecret
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
timezone: America/New_York # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    feature_image: "/assets/banner.webp"

# 7. Site settings
title: Tobsecret's homepage
description: Programming Blog & Dominion sets
encoding: utf-8 # Make sure the encoding is right
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
lang: en-GB # Set the site language
url: "https://tobsecret.github.io" # Site url, also used in jekyll-seo-tag

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: CV
  url: /cv/
- title: Dominion
  url: /dominion/
- title: Search
  url: /search/

navigation_footer: true

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/tschraink
  GitHub: https://github.com/tobsecret
  RSS: /feed.xml